spring:
  application:
    name: 22683901_NguyenHoVietKhoa_Tuan7
  datasource:
    url: jdbc:mariadb://localhost:3307/shopping
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      platform: mariadb
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  messages:
    encoding: UTF-8
    basename: home
